// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwnzllhereniufnnvgds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3bnpsbGhlcmVuaXVmbm52Z2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMzg1OTYsImV4cCI6MjA4NDkxNDU5Nn0.PGOR3x2X26oZXgCsUcl5v1xqDCk0DIX6-of8VcKkm2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});